[profile.default]
optimizer_runs = 200
src = "src"
out = "out"
libs = ["lib", "../../liquidity-launcher/lib"]
allow_paths = ["../../liquidity-launcher"]
bytecode_hash = "none"
via_ir = true

[lint]
lint_on_build = false
